# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 01:37
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yyfeed', '0002_auto_20170106_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
