# Generated by Django 2.0.1 on 2018-01-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yyfeed', '0004_auto_20171214_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='item_id',
            field=models.CharField(max_length=128),
        ),
    ]
