# Generated by Django 2.0.1 on 2018-01-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yyfeed', '0005_auto_20180109_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='limit',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
